WIP Major rewrite to better handle errors, interactive modes, and inputs with prefilled codes. `-t` print temporarily broken and does not support multi input yet. fzf commands temporarily broken in -p

diff --git a/we b/we
--- a/we
+++ b/we
@@ -9,7 +9,7 @@
 
 VERSION=0.3
 WE_DIR="$(dirname "$(readlink -f "$0")")"
-FZFOPTS=( --height=100% --layout=reverse --cycle --border --marker='*' )
+FZFOPTS=( --height=90% --layout=reverse --cycle --border --marker='*' )
 
 # Internal functions
 has() {
@@ -31,13 +31,43 @@ _pemx() {
     exit 1
 }
 
+findcmd() {
+    find . -type f -printf '%f\n' | sort
+}
+
+fzfcmd() {
+    fzf --ansi \
+        --header=$'Ret  print & exit
+C-e  edit
+C-x  edit beautified
+     dep: kakoune
+C-v  view table/json
+C-r  ripgrep
+     dep: rga-fzf
+?    toggle preview\n\n' \
+        --preview="$1" \
+        --preview-window="right:80%:wrap:cycle" --delimiter / --with-nth -1 \
+        --bind="?:toggle-preview" \
+        --bind="ctrl-r:execute(rga-fzf {} '')" \
+        --bind="ctrl-e:execute(${EDITOR:-vim --not-a-term} {} </dev/tty)" \
+        --bind="ctrl-x:execute(kak -e 'execute-keys <%><|>jq<ret><g><e>' {} </dev/tty)" \
+        --bind="$2" \
+        --bind="$3" \
+        "${FZFOPTS[@]}" \
+        "$4"
+}
+ 
 version() {
     # Print version and working directory
     _pht "$(basename "$0") $VERSION"
     _pht "Working directory: '$WE_DIR'"
 }
 
-usage() {
+quit() {
+    exit 0
+}
+
+show-help() {
     # Show help
     _pht "Scrap worldwide events from rsoe-edis.org"
     _pht
@@ -76,7 +106,7 @@ setup() {
         chmod +x "$WE_DIR/scripts/$code.py";
     done < "$WE_DIR"/setup/codes.txt
     printf "Generating scrap scripts for the following codes…\n"
-    listcodes
+    list-codes
     printf "\n$(find "${WE_DIR}"/scripts/*.py -maxdepth 1 -type f 2>/dev/null | wc -l) scrap scripts created in ${WE_DIR}/scripts/. \033[32;1m%s\033[0m\n" '✔'
     
     # Check if $(basename "$0") already in PATH, else create symlink into ~/.local/bin/
@@ -86,7 +116,7 @@ setup() {
        if ! [ "$REPLY" = "n" ] || [ "$REPLY" = "N" ] || \
            [ "$REPLY" = "no" ] || [ "$REPLY" = "NO" ]; then
            ln -s "$WE_DIR"/we "$HOME"/.local/bin/we
-           printf "Done. You can now run '$(basename "$0")' from anywhere. \033[32;1m%s\033[0m\n" '✔'
+           printf "Done. \033[32;1m%s\033[0m You can now run '$(basename "$0")' from anywhere.\n" '✔'
        fi
     fi
 }
@@ -94,73 +124,80 @@ setup() {
 get() {
     # Scrap data, use fzf if no code provided
     export WE_DIR
+    cd "$WE_DIR"/scripts 2>/dev/null || exitonerror "no scrap scripts generated yet. Run '$(basename "$0") -s first.'"
     mkdir -p "$WE_DIR"/data
     if [ -z "$1" ]; then
-        nscripts="$(find "$WE_DIR"/scripts/ -type f -printf '%f\n' | wc -l)"
+        nscripts="$(findcmd | wc -l)"
         if [ "$nscripts" -eq "0" ]; then
-            printf '\033[31;1mErr:\033[0m %s\n' "there are no scrap scripts yet, please run '$(basename "$0") --setup' first."
+            exitonerror "no scrap scripts generated yet. Run '$(basename "$0") -s' first."
         else
-            cd "$WE_DIR"/scripts
-            cod=( $(find . -type f -printf '%f\n' | sed s/.py// | sort | \
+            cod=( $(findcmd | sed s/.py// | \
                 fzf "${FZFOPTS[@]}" --multi --header=$'Pick event type(s):\nTab  multi-selection\n\n' | xargs) )
-            for i in "${cod[@]}"; do printf 'Scraping %s… ' "$i" && python3 $i.py; done
+            for i in "${cod[@]}"
+                do printf 'Scraping %s… ' "$i" && python3 $i.py
+            done
+            quit
         fi
     else
-        cd "$WE_DIR"/scripts
-        cod=( $(echo "$@" | tr '[:lower:]' '[:upper:]' | xargs) )
-        echo $cod
-        for i in "${cod[@]}"; do printf 'Scraping %s… ' "${cod[i]}" ; python3 $i.py; done
-        if ! [ -f "${WE_DIR}/scripts/${cod}.py" ]; then
-            printf '\033[31;1mErr:\033[0m %s\n' "there is no scrap script for $cod yet, make sure this code is available in '$(basename "$0") -l' and regenerate scripts with '$(basename "$0") -s'."
+        cod=( $(echo "$@" | tr '[:lower:]' '[:upper:]' | xargs) )         
+        unset 'cod[0]' ; unset 'cod[-1]'
+        if [ "${#cod[@]}" -eq "0" ]; then
+            get
         fi
+        for i in "${cod[@]}"
+            do printf 'Scraping %s… ' "$i"
+            python3 "$i".py 2>/dev/null
+            if ! [ -f "$i.py" ]; then
+                printf ' \033[31;1mErr:\033[0m %s\n' "no scrap script for $i yet. Make sure this code is available in '$(basename "$0") -l' and regenerate scripts with '$(basename "$0") -s'."
+            fi
+        done
     fi
-}
-
-fzfcmd() {
-    find . -type f -printf '%f\n' | sort | fzf --ansi \
-        --header=$'Ret  print & exit
-C-e  edit
-C-x  edit beautified
-     dep: kakoune
-C-v  view table/json
-C-r  ripgrep
-     dep: rga-fzf
-?    toggle preview\n\n' \
-        --preview="$1" \
-        --preview-window="right:80%:wrap:cycle" --delimiter / --with-nth -1 \
-        --bind="?:toggle-preview" \
-        --bind="ctrl-r:execute(rga-fzf {} '')" \
-        --bind="ctrl-e:execute(${EDITOR:-vim --not-a-term} {} </dev/tty)" \
-        --bind="ctrl-x:execute(kak -e 'execute-keys <%><|>jq<ret><g><e>' {} </dev/tty)" \
-        --bind="$2" \
-        --bind="$3"
 }
 
 print() {
     # Show scraped data, use fzf if no code provided
-    cd "$WE_DIR"/data || exit
+    cd "$WE_DIR"/data 2>/dev/null || exitonerror "no data scraped yet. Run '$(basename "$0") -g first.'"
     if [ -z "$1" ]; then
-        ndata="$(find . -type f -printf '%f\n' | wc -l)"
+        ndata="$(findcmd | wc -l)"
         if [ "$ndata" -eq "0" ]; then
-            printf '\033[31;1mErr:\033[0m %s\n' "there are no data files yet, please run '$(basename "$0") --get' first."
+            exitonerror "no data scraped yet. Run '$(basename "$0") -g' first."
         else
-        fzfcmd "cat {} | jq" "enter:execute(cat {} | jq)+abort" "ctrl-v:execute(cat {} | jq | jtbl -t | less -S)"
+            cod=( $(findcmd | \
+            fzfcmd "cat {} | jq" "ctrl-p:execute(cat {} | jq)+abort" "ctrl-v:execute(cat {} | jq | jtbl -t | less -SN)" "--multi") )
+            for i in "${cod[@]}"
+                do printf '\n%s\n--------\n' "$i"
+                jq < "$i"
+            done
+            quit
+#        fzfcmd "cat {} | jq" "enter:execute(cat {} | jq)+abort" "ctrl-v:execute(cat {} | jq | jtbl -t | less -S)"
+#--multi --header=$'Pick event type(s):\nTab  multi-selection\n\n' | xargs) )
         fi
     else
-        cod=$(echo "$1" | tr '[:lower:]' '[:upper:]')
-        jq < "$WE_DIR"/data/"$cod".json
+        cod=( $(echo "$@" | tr '[:lower:]' '[:upper:]' | xargs) )
+        unset 'cod[0]' ; unset 'cod[-1]'
+        if [ "${#cod[@]}" -eq "0" ]; then
+            print
+        fi
+        for i in "${cod[@]}"
+            do printf '\n%s\n--------\n' "$i.json"
+            cat "$i".json 2>/dev/null | jq
+            if ! [ -f "$i.json" ]; then
+                printf ' \033[31;1mErr:\033[0m %s\n' "no data scraped for $i yet. Run '$(basename "$0") -g $i' first."
+            fi
+        done
     fi
 }
 
 table() {
     # Show scraped data as table, use fzf if no code provided
-    cd "$WE_DIR"/data || exit
+    cd "$WE_DIR"/data 2>/dev/null || exitonerror "no data scraped yet. Run '$(basename "$0") -g first.'"
     if [ -z "$1" ]; then
-        ndata="$(find . -type f -printf '%f\n' | wc -l)"
+        ndata="$(findcmd | wc -l)"
         if [ "$ndata" -eq "0" ]; then
-            printf '\033[31;1mErr:\033[0m %s\n' "there are no data files yet, please run '$(basename "$0") --get' first."
+            exitonerror "no data scraped yet. Run '$(basename "$0") --get' first."
         else
-        fzfcmd "cat {} | jq | jtbl -t" "enter:execute(cat {} | jq | jtbl -t)+abort" "ctrl-v:execute(cat {} | jq | less -S)"
+        findcmd | \
+            fzfcmd "cat {} | jq | jtbl -t" "ctrl-p:execute(cat {} | jq | jtbl -t)+abort" "ctrl-v:execute(cat {} | jq | less -SN)" "--multi"
         fi
     else
         cod=$(echo "$1" | tr '[:lower:]' '[:upper:]')
@@ -168,55 +205,75 @@ table() {
     fi
 }
 
-listcodes() {
+list-codes() {
     # List available codes
     tr '\n' '\t' < "$WE_DIR"/setup/codes.txt | fold -w 80 -s
+    printf "\n"
 }
 
-updatecodes() {
+update-codes() {
     # Fetch currently active codes online
-    printf "Fetching codes is not implemented yet, sadly. :< "
+    printf "Fetching codes is not implemented yet, sadly. :<\n"
 }
 
-rmscripts() {
+exitonerror() {
+    printf '\033[31;1mErr:\033[0m %s\n %s' "$1" && exit
+}
+
+rm-scripts() {
     # Remove scrap scripts
-    printf '\033[33;1mWrn:\033[0m %s' "remove $(find "${WE_DIR}"/scripts/*.py -maxdepth 1 -type f 2>/dev/null | wc -l) scrap scripts? [y/N] " && read -r
-    if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ] || \
-        [ "$REPLY" = "yes" ] || [ "$REPLY" = "YES" ]; then
-        rm "$WE_DIR"/scripts/*.py 2>/dev/null
-        printf "${WE_DIR}/scripts/ directory cleaned. \033[32;1m%s\033[0m\n" '✔'
-        printf "Run '%s' to regenerate scrap scripts.\n" "$(basename "$0") -s"
-    fi
-
-    # Check if $(basename "$0") already in PATH, else create symlink into ~/.local/bin/
-    has we && in_path="true"
-    if [ "$in_path" == "true" ]; then
-       printf "\nAlso remove '%s' symbolic link from your PATH? [y/N] " "$(basename "$0")" && read -r
-       if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ] || \
-           [ "$REPLY" = "yes" ] || [ "$REPLY" = "YES" ]; then
-           rm "$HOME"/.local/bin/we
-           printf "Done. \033[32;1m%s\033[0m\n" '✔'
-       fi
+    cd "$WE_DIR"/scripts 2>/dev/null || exitonerror "no scrap scripts generated yet. Run '$(basename "$0") -s first.'"
+    if [ -z "$1" ]; then
+        printf '\033[33;1mWrn:\033[0m %s' "remove $(findcmd 2>/dev/null | wc -l) scrap scripts? [y/N] " && read -r
+        if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ] || \
+            [ "$REPLY" = "yes" ] || [ "$REPLY" = "YES" ]; then
+            rm "$WE_DIR"/scripts/*.py 2>/dev/null
+            printf "${WE_DIR}/scripts/ directory cleaned. \033[32;1m%s\033[0m\n" '✔'
+            printf "Run '%s' to regenerate scrap scripts.\n" "$(basename "$0") -s"
+            # Check if $(basename "$0") already in PATH, else create symlink into ~/.local/bin/
+            has we && in_path="true"
+            if [ "$in_path" == "true" ]; then
+               printf "\nAlso remove '%s' symbolic link from your PATH? [y/N] " "$(basename "$0")" && read -r
+               if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ] || \
+                   [ "$REPLY" = "yes" ] || [ "$REPLY" = "YES" ]; then
+                   rm "$HOME"/.local/bin/we
+                   printf "Done. \033[32;1m%s\033[0m\n" '✔'
+               fi
+            fi
+        fi
+    else
+        cod=$(echo "$1" | tr '[:lower:]' '[:upper:]')
+        if ! [ -f "${cod}.py" ]; then
+            printf '\033[31;1mErr:\033[0m %s\n' "no scrap script for $cod."
+        else
+            printf '\033[33;1mWrn:\033[0m %s' "delete $cod.py? [Y/n] " && read -r
+            if ! [ "$REPLY" = "n" ] || [ "$REPLY" = "N" ] || \
+                [ "$REPLY" = "no" ] || [ "$REPLY" = "NO" ]; then
+               rm "$cod".py
+               printf "${WE_DIR}/scripts/$cod.py removed. \033[32;1m%s\033[0m\n" '✔'
+            fi
+        fi
     fi
 }
 
-cleardata() {
+clear-data() {
     # Remove data
+    cd "$WE_DIR"/data 2>/dev/null || exitonerror "no data scraped yet. Run '$(basename "$0") -g first.'"
     if [ -z "$1" ]; then
-        printf '\033[33;1mWrn:\033[0m %s' "delete $(find "${WE_DIR}"/data/*json -maxdepth 1 -type f 2>/dev/null | wc -l) previously scraped data file(s)? This cannot be undone. Type YES to confirm. " && read -r
+        printf '\033[33;1mWrn:\033[0m %s' "delete $(findcmd 2>/dev/null | wc -l) previously scraped data file(s)? This cannot be undone. Type YES to confirm. " && read -r
         if [ "$REPLY" = "YES" ]; then
            rm "$WE_DIR"/data/*.json
            printf "${WE_DIR}/data/ directory cleaned. \033[32;1m%s\033[0m\n" '✔'
         fi
     else
         cod=$(echo "$1" | tr '[:lower:]' '[:upper:]')
-        if ! [ -f "${WE_DIR}/data/${cod}.json" ]; then
+        if ! [ -f "${cod}.json" ]; then
             printf '\033[31;1mErr:\033[0m %s\n' "$cod.json was not scraped yet."
         else
             printf '\033[33;1mWrn:\033[0m %s' "delete $cod.json? This cannot be undone. [y/N] " && read -r
             if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ] || \
                 [ "$REPLY" = "yes" ] || [ "$REPLY" = "YES" ]; then
-               rm "$WE_DIR"/data/"$cod".json
+               rm "$cod".json
                printf "${WE_DIR}/data/$cod.json removed. \033[32;1m%s\033[0m\n" '✔'
             fi
         fi
@@ -225,9 +282,9 @@ cleardata() {
 
 interactive() {
     # Use fzf to manipulate program options
-    usage ; exit 0 # Temporary, just to avoid breaking until the option is fully implemented
-#    arg="$(fzf < $(printf "get\nprint\ntable\nlistcodes\nsetup\nupdatecodes\nrm-scripts\nclear-data\nversion\nhelp"))"
-#    we $arg
+    cmd=$(echo "get print table list-codes setup update-codes rm-scripts clear-data version show-help quit" \
+    | tr ' ' '\n' | fzf "${FZFOPTS[@]}")
+    eval $cmd
 }
 
 # Dependency check
@@ -246,27 +303,27 @@ fi
     "-g"|"--get")
         get "$@" "$WE_DIR" ; exit ;;
     "-p"|"--print")
-        print "$2" "$WE_DIR" ; exit ;;
+        print "$@" "$WE_DIR" ; exit ;;
     "-t"|"--table")
         table "$2" "$WE_DIR" ; exit ;;
     "-l"|"--list-codes")
-        listcodes "$WE_DIR" ; exit ;;
+        list-codes "$WE_DIR" ; exit ;;
     "-s"|"--setup")
         setup "$WE_DIR" ; exit ;;
     "-u"|"--update-codes")
-        updatecodes "$WE_DIR" ; exit ;;
+        update-codes "$WE_DIR" ; exit ;;
     "-R"|"--rm-scripts")
-        rmscripts "$WE_DIR" ; exit ;;
+        rm-scripts "$2" "$WE_DIR" ; exit ;;
     "-C"|"--clear-data")
-        cleardata "$2" "$WE_DIR" ; exit ;;
+        clear-data "$2" "$WE_DIR" ; exit ;;
     "-i"|"--interactive")
-        interactive "$2" "$WE_DIR" ; exit ;;
+        interactive "$WE_DIR" ; exit ;;
     "-v"|"--version")
         version "$WE_DIR" ; exit 0 ;;
     "-h"|"--help")
-        usage ; exit 0 ;;
+        show-help ; exit 0 ;;
     -*)
         _pemx "$1 is not a supported option." ;;
     *)
-        usage ; exit 0 ;;
+        quit ;;
 esac
